version: '3.1'
services:

  laravel:
    build: ./php
    container_name: laravel
    restart: always
    volumes:
      - ./php/www/:/var/www/html
    links:
      - db
    ports:
      - 81:80
    environment:
      - TZ=Asia/Bangkok

  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql/config/:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootp@ssw0rd
      - MYSQL_DATABASE=test
      - MYSQL_USER=jesse
      - MYSQL_PASSWORD=p@ssw0rd
      - TZ=Asia/Bangkok
